/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

const fs = require('fs');
const path = require('path');


/**
 * 按月份组织文档
 * @param {string} dirName - 目录名称（相对于 docs 文件夹）
 * @returns {Array} 侧边栏配置
 */
function generateSidebarByMonth(dirName) {
  const dirPath = path.join(__dirname, 'docs', dirName);

  // 检查目录是否存在
  if (!fs.existsSync(dirPath)) {
    return [{type: 'autogenerated', dirName: dirName}];
  }

  const files = fs.readdirSync(dirPath);

  // 按月份分组
  const monthGroups = {};
  const otherFiles = [];

  // 日期格式正则：YYYY-MM-DD-xxx.md 或 YYYY-MM-DD xxx.md 或 YYYY年...
  const datePattern = /^(\d{4})-(\d{2})-(\d{2})[-\s]/;
  const yearPattern = /^(\d{4})年/;

  files.forEach(file => {
    if (!file.endsWith('.md')) return;

    const match = file.match(datePattern);
    if (match) {
      const [, year, month] = match;
      const monthKey = `${year}-${month}`;

      if (!monthGroups[monthKey]) {
        monthGroups[monthKey] = [];
      }

      // 使用不带扩展名的文件名作为 ID
      const docId = `${dirName}/${file.replace('.md', '')}`;
      monthGroups[monthKey].push({
        file,
        docId,
        year,
        month
      });
    } else {
      // 检查是否有年份前缀（如：2023-08-26-年度团建后感悟.md）
      const yearMatch = file.match(yearPattern);
      if (yearMatch) {
        const year = yearMatch[1];
        const monthKey = `${year}-00`; // 只有年份的放在该年的"其他"组

        if (!monthGroups[monthKey]) {
          monthGroups[monthKey] = [];
        }

        const docId = `${dirName}/${file.replace('.md', '')}`;
        monthGroups[monthKey].push({
          file,
          docId,
          year,
          month: '00'
        });
      } else {
        // 没有日期前缀的文件
        otherFiles.push(`${dirName}/${file.replace('.md', '')}`);
      }
    }
  });

  // 如果没有任何带日期的文件，使用自动生成
  if (Object.keys(monthGroups).length === 0 && otherFiles.length === files.filter(f => f.endsWith('.md')).length) {
    return [{type: 'autogenerated', dirName: dirName}];
  }

  // 转换为侧边栏配置
  const sidebar = [];

  // 按年月倒序排列（最新的在前面）
  const sortedMonths = Object.keys(monthGroups).sort().reverse();

  sortedMonths.forEach(monthKey => {
    const items = monthGroups[monthKey];
    const [year, month] = monthKey.split('-');

    // 按日期倒序排列
    items.sort((a, b) => b.file.localeCompare(a.file));

    // 确定标签
    let label;
    if (month === '00') {
      label = `${year}年`;
    } else {
      label = `${year}年${parseInt(month)}月`;
    }

    sidebar.push({
      type: 'category',
      label: label,
      collapsed: false,
      items: items.map(item => item.docId)
    });
  });

  // 添加其他文件（没有日期前缀的）
  if (otherFiles.length > 0) {
    sidebar.push({
      type: 'category',
      label: '其他',
      collapsed: true,
      items: otherFiles.sort()
    });
  }

  return sidebar;
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [{type: 'autogenerated', dirName: '.'}],

  // 所有目录都按月份组织
  llm: generateSidebarByMonth('llm'),

  k8s: generateSidebarByMonth('k8s'),

  ide: generateSidebarByMonth('ide'),

  blog: generateSidebarByMonth('blog'),

  book: generateSidebarByMonth('book'),

  note: generateSidebarByMonth('note'),

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;




