/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [{type: 'autogenerated', dirName: '.'}],

  llm: [{type: 'autogenerated', dirName: 'llm'}],

  k8s: [{type: 'autogenerated', dirName: 'k8s'}],

  ide: [{type: 'autogenerated', dirName: 'ide'}],

  blog: [{type: 'autogenerated', dirName: 'blog'}],

  note: [{type: 'autogenerated', dirName: 'note'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial/create-a-document'],
    },
  ],
   */
};

export default sidebars;
